# Generated by Django 3.2.5 on 2022-02-26 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20220226_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='likeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='Likes',
        ),
        migrations.DeleteModel(
            name='LikeView',
        ),
        migrations.AddField(
            model_name='likemember',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_like', to='posts.post'),
        ),
        migrations.AddField(
            model_name='likemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(through='posts.likeMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likemember',
            unique_together={('post', 'user')},
        ),
    ]
