# Generated by Django 3.2.5 on 2022-03-01 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20220301_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
