# Generated by Django 3.2.5 on 2022-03-01 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_alter_post_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(through='posts.PostMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
